
FROM alpine:latest

RUN apk add -U --no-cache \
    neovim git tmux openssh-client \
    bash wget curl less man \
    openjdk11

# open jdk 11 is just a placeholder,
# we actually want GraalVM or anything that
# can run Java 20 (and Java 21 later, if possible) 

