FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y build-essential git wget libssl-dev zlib1g-dev \
                       libbz2-dev libreadline-dev libsqlite3-dev \
                       libncursesw5-dev xz-utils tk-dev libxml2-dev \
                       libxmlsec1-dev libffi-dev liblzma-dev \
                       ca-certificates time && \
    update-ca-certificates

