CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     PROGRAM GUESS A NUMBER BETWEEN 1 AND 100
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      PROGRAM GUESSNUM
        INTEGER NUMBER, GUESS

C --- ORIGINAL ASKED USER TO PROVIDE SEED
C        INTEGER SEED
C        PRINT *, 'ENTER A RANDOM NUMBER SEED'
C        READ *, SEED
C        CALL SRAND(SEED)

C -- NOW IT USES THE SYSTEM UNIX TIME AS SEED

        CALL SRAND(TIME())

        NUMBER = INT( RAND(0) * 100 + 1 )

        PRINT *, 'GUESS A NUMBER FROM 1 TO 100'
21      READ *, GUESS

        IF (GUESS.LT.NUMBER) THEN
          PRINT *, 'TOO LOW'
        ELSE IF (GUESS.GT.NUMBER) THEN
          PRINT *, 'TOO HIGH'
        ENDIF

        IF (GUESS.NE.NUMBER) GOTO 21

        PRINT *, 'YOU GOT IT!'
        END

