---
- name: Build and run a Java container with Podman
  hosts: localhost
  tasks:
    - name: Generate a random number
      set_fact:
        random_number: "{{ 9999 | random }}"

    - name: Remove existing container if it exists
      command: >
        podman rm -f java_test_container_{{ random_number }}
      ignore_errors: yes
      failed_when: false

    - name: Check if Podman network exists
      command: >
        podman network inspect podman
      register: network_inspect
      ignore_errors: yes

    - name: Create Podman network if it does not exist
      command: >
        podman network create podman
      when: network_inspect.rc != 0

    - name: Run Java container interactively with Podman and mount the test-code directory
      command: >
        podman run -it --name java_test_container_{{ random_number }}
        -v /home/edo9k/Documentos/repos/learn:/usr/src/myapp
        docker.io/library/openjdk:latest
        /bin/bash

